# Copyright (c) 2022, WSO2 LLC. (https://www.wso2.com) All Rights Reserved.
#
# WSO2 LLC. licenses this file to you under the Apache License,
# Version 2.0 (the "License"); you may not use this file except
# in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied. See the License for the
# specific language governing permissions and limitations
# under the License.

wso2:
  subscription:
    imagePullSecrets: ""
    
  apk:
    webhooks:
      validatingwebhookconfigurations : true
      mutatingwebhookconfigurations : true
    auth:
      enabled: true
      enableServiceAccountCreation: true
      enableClusterRoleCreation: true
      serviceAccountName: wso2apk-platform
      roleName: wso2apk-role
    rootCertificate:
      tlsCert: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMvVENDQWVXZ0F3SUJBZ0lVZDRuanY4eVNQZ283dDBGMWUyYUpFbzlUcFE0d0RRWUpLb1pJaHZjTkFRRUwKQlFBd0RqRU1NQW9HQTFVRUF3d0RZWEJyTUI0WERUSXpNRE13T1RBNE1UWXpORm9YRFRNek1ETXdOakE0TVRZegpORm93RGpFTU1Bb0dBMVVFQXd3RFlYQnJNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDCkFRRUExRzlCQWNWYTNhTWVteEVSWStKOFVtSC9XOEpwY0VPdGRlTlg1WU5paG5OT1h0bHZoU3pGek9QYUs5N1AKcjRJcUdBU2JWTmlSKzFKNldFb2kvYjZaSlR4MHEzWVVuMFlsUUpyejdnMjBUZG9HSmp4R1ZXem4wRVc0YmVIWApHcTYwdlhMZjR0M21sTENMR0lLM2tKVFdBb1J6ZDc0ZGpWNys1djBCbS82S0JCQVdjdTVVYk9EOUtScE9zeEdNCm4zWjAxMDNvQUdWaXlxODRRdEZ2aFhWTld0dERMZTJqVS83bzQyZGRhSm96Ukw5eisxQWVwZG9XUHlKWklacVUKYlhjR0FrN2lkazdjLzhkS014d0FtM0NWL1d2Z1dyVks1UitZVGlHcVJmNXBkOVdXQ3lkRVZRa05xQ1pnVFBOeQpCVFJ2SG81Mm9uUG5UNkFMdE1JMG1uV0x0UUlEQVFBQm8xTXdVVEFkQmdOVkhRNEVGZ1FVenhjQThjZUNGNXQrCnZQZU9wWWJpMTFDV2p3Y3dId1lEVlIwakJCZ3dGb0FVenhjQThjZUNGNXQrdlBlT3BZYmkxMUNXandjd0R3WUQKVlIwVEFRSC9CQVV3QXdFQi96QU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFGQ0tkNXg4ejY0cDFqOUJub1NBbApKSnVOejR1V2p2L1lLOTRCM3MzS1VrWE9Yakh1THVhemtTc3MyVUhGYitLZUxkNnZoaW1NNVFxa0ZzVUVNc25DCjhSeUJaUDU4a2doY0x6SmxkNVVpd2xuci9SdU9BTnZjdjRlS1Nhdnd1NS9BQlh1TVVRYi9Hdkt0V1BycjJWYkoKVUxnM3A3TkdpZ1hISGc4NGVWTUE3b05YMVo1UjJjUzRJU2tsV1htNVNwTVBoK1NOQ2dxd3FoeFJOWUoySjBFWgpxbHA0b2ZRRzNHSjcySitEUkhsTnVqV0Vza1A1SUpqdzZ3OFEwempYeDI2eWVsR2UyK1RNNkJCN1BwQ042a05VCnpIbzJrLzU3NWJ1MmlaenRuWVZtRTc0SDFXM2NYSjdjMHE4MnVVRnZkVytGbFJ0bStPUElpSUdLNzRsRmlaTkIKT1E9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg=="
      tlsKey: "LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2UUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktjd2dnU2pBZ0VBQW9JQkFRRFViMEVCeFZyZG94NmIKRVJGajRueFNZZjlid21sd1E2MTE0MWZsZzJLR2MwNWUyVytGTE1YTTQ5b3Izcyt2Z2lvWUJKdFUySkg3VW5wWQpTaUw5dnBrbFBIU3JkaFNmUmlWQW12UHVEYlJOMmdZbVBFWlZiT2ZRUmJodDRkY2FyclM5Y3QvaTNlYVVzSXNZCmdyZVFsTllDaEhOM3ZoMk5YdjdtL1FHYi9vb0VFQlp5N2xSczRQMHBHazZ6RVl5ZmRuVFhUZWdBWldMS3J6aEMKMFcrRmRVMWEyME10N2FOVC91ampaMTFvbWpORXYzUDdVQjZsMmhZL0lsa2htcFJ0ZHdZQ1R1SjJUdHoveDBvegpIQUNiY0pYOWErQmF0VXJsSDVoT0lhcEYvbWwzMVpZTEowUlZDUTJvSm1CTTgzSUZORzhlam5haWMrZFBvQXUwCndqU2FkWXUxQWdNQkFBRUNnZ0VBQ1VMRVdiaHB5cW0yeHRuS29Va1pWRm9UVU1PNzV2bjhVTnhWVTVzVHEzclIKV3M4dHptZHlSQWxXMUh6Rkh3aVVuekZzT0JtczI0RHY5bk5jN1NUbTlqbVplSFFRV0JVdHdKQkF2QXI2NWozdgo4TERGL0NsZ1BiTWNaQ1hwUTYrRUQ1STNjbU5zRHVWWFd2MHYxV3kzbTZwOGdpYldrUGdvTXBlcS8wcnNaMXJiCjB6TDhuNkpENUtxc3JjWE5WODNObTZqUmxUMzJZWGZreHpwczhpME1PZGYyLzllQmVrMC93N2xBTU0wNFQ3dXMKNWRHeVRFNHo3eThYVndscmF6WFlMM2VUL3RDOHY4M3BrWXNlOWdBZ2I4Z3MrRmlhTUc3WG1sMmpmY05YV1I0ZwpHRmRSMmRJVlNQbnJwdldLajNrS0IwVXFsVVplakp2WkhhQlk2cStDd1FLQmdRRGRKbFB3MUFONjhncVVMdjB2CmltMWNyVTJneS9kbzZpWjl0Y05MdjgxblMzS1JtRVllKzBTYzZZR3dNQWtPWjd0S1BTMnNsRU9IUDUzQjVseU8KakttSlhkQXBvZVUzSW5lOW5kRGs3TEoxNVpsTkFzNXlWb1pjdzdINHp2YTIwM0c2UDFnZWpja2RpOWVicDFnVAorUVpNSmZjdHJtaExDaDhQR1ZzZDRPaFFNUUtCZ1FEMTZWYVRDQ243MElESFNnLzJia1M3NjJzK2dmcHJpK3hCCjE4UmhMOVowL1RQQVl2dUpqNWNUaHh6S2hGWG53ZDRHVGZ4eFdnaURsV3lIb1BjRDhLT2JLM1htT1ZUUEg2WDcKNjdNdTc4bWxLZlVZY3VrM244ekFmc1FkQzBBNmNRRVlhcVFIMW4wSjZVM255RnNwL0hJWis1NjhQQmQwT0dMUQprWmdrc3oyMnhRS0JnR01uZEN0ZVk5RVVCTG83OXprQmo5Y2x2TkNEb3dKZk9iTFRkQ1RhY25ZRjFmQ0JuYTcyCmFlVVFyUjBaN0hXUS9PQmtYYjRyRzd2Z1FoTlYvZG5NSjVkM2dJV3FHT09IaUxoenNkMXlZdkdKYUJxblQzamsKWW9ubEZEN0NUTXZjTWZtWHZTSzEzNTVudk53RlEvQndqdXBGZTNYMzVMc0FacnlXV2N3anN3V0JBb0dBYTNidApQcFB5eFBqNVRoNHZtNkhVcDhyWnN4ZGFPR1dOZWJpeE9VZU9rTkdXTEIwVmo2Z1FmWmd1SE5KNE9DK2d0MkNkClVXdm5ESm5nTStWRURaUzc2ck96Y2tqYnB5aE5nU29meEFOR084ZDZOSlVERml2ZmJyLzNORG9XZDNPcTV1Q3oKampsTnEyY3BoSUVxVmM3Y2pqNUh3RHNDaE9lZlIwWlpGckM5NTRFQ2dZRUFwZHloY1FiL1o0WXJ5bHJmelJycAovR0RjdVg5TlQxWDdtT2tCamExVXUvSTV6ZFVMYzkrNjZUc3IyTEhiVUdtUkhnTGx4NHo1U1dIeVJiTnhOUENwCkN1Q0svdkh6TlN6YlZVeDRUSzBYZHJHOWI5SHRXcU4yU0pERk9tSXBVYUJPd25SYThxa3hwSTF3YWRsT2ZYejUKUFdIQ3RJcWRkdlRkeG50TnpxekRnVzg9Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K"
    listener:
      hostname: "api.am.wso2.com"
      # secretName: "idp-tls"
    idp:
      issuer: "https://idp.am.wso2.com/token"
      authorizeEndpoint: "https://idp.am.wso2.com:9095/oauth2/authorize"
      tokenEndpoint: "https://idp.am.wso2.com:9095/oauth2/token"
      revokeEndpoint: "https://idp.am.wso2.com:9095/oauth2/revoke"
      usernameClaim: "sub"
      organizationClaim: "organization"
      # organizationResolver: "controlPlane" # controlplane,none
      credentials:
        secretName: "wso2apk-idp-credentials"
      # tls:
      #   secretName: "wso2apk-idp-certificates"
      #   fileName: "idp.crt"
      # signing:
      #   jwksEndpoint: "https://idp.am.wso2.com:9095/oauth2/jwks"
      #   secretName: "wso2apk-idp-signing"
      #   fileName: "idp.crt"
    dp:
      enabled: true
      gateway:
        listener:
          hostname: "gw.wso2.com"
          # secretName: "idp-tls"
      # partitionServer:
      #   enabled: false
      #   host: "https://control-plane-wso2-apk-partition-server.control-plane.svc.cluster.local"
      #   serviceBasePath: "/api/publisher/v1"
      #   partitionName: "default"
      #   hostnameVerificationEnable: true
      #   tls:
      #     secretName: "partition-server-cert"
      #     fileName: "certificate.crt"
      #   headers:
      #     - name: "apiKey"
      #       value: "123-456-789"
      configdeployer:
        enabled: true
        deployment:
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "1028Mi"
              cpu: "1000m"
          readinessProbe:
            initialDelaySeconds: 20
            periodSeconds: 20
            failureThreshold: 5
          livenessProbe:
            initialDelaySeconds: 20
            periodSeconds: 20
            failureThreshold: 5
          strategy: RollingUpdate
          replicas: 1
          imagePullPolicy: Always
          image: wso2/config-deployer-service:1.0.0-beta
          # configs:
          #   tls:
          #     secretName: "my-secret"
          #     certKeyFilename: "tls.key"
          #     certFilename: "certchain.crt"
      adapter:
        deployment:
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "1028Mi"
              cpu: "1000m"
          readinessProbe:
            initialDelaySeconds: 20
            periodSeconds: 20
            failureThreshold: 5
          livenessProbe:
            initialDelaySeconds: 20
            periodSeconds: 20
            failureThreshold: 5
          strategy: RollingUpdate
          replicas: 1
          imagePullPolicy: Always
          image: wso2/adapter:1.0.0-beta
          security:
            sslHostname: "adapter"
#        logging:
#          level: "INFO" # LogLevels can be "DEBG", "FATL", "ERRO", "WARN", "INFO", "PANC"
#          logFormat: "TEXT" # Values can be "JSON", "TEXT"
        # configs:
        #   apiNamespaces:
        #     - "apk-v12"
        #   tls:
        #     secretName: "adapter-cert"
        #     certKeyFilename: ""
        #     certFilename: ""
      commonController:
        deployment:
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "1028Mi"
              cpu: "1000m"
          readinessProbe:
            initialDelaySeconds: 20
            periodSeconds: 20
            failureThreshold: 5
          livenessProbe:
            initialDelaySeconds: 20
            periodSeconds: 20
            failureThreshold: 5
          strategy: RollingUpdate
          replicas: 1
          imagePullPolicy: Always
          image: wso2/common-controller:1.0.0-beta
          security:
            sslHostname: "commoncontroller"
      ratelimiter:
        enabled: true
        deployment:
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "1028Mi"
              cpu: "1000m"
          readinessProbe:
            initialDelaySeconds: 20
            periodSeconds: 20
            failureThreshold: 5
          livenessProbe:
            initialDelaySeconds: 20
            periodSeconds: 20
            failureThreshold: 5
          strategy: RollingUpdate
          replicas: 1
          imagePullPolicy: Always
          image: wso2/ratelimiter:1.0.0-beta
          security:
            sslHostname: "ratelimiter"
          # configs:
          #   tls:
          #     secretName: "ratelimiter-cert"
          #     certKeyFilename: ""
          #     certFilename: ""
          #     certCAFilename: ""
      gatewayRuntime:
        deployment:
          replicas: 1
          router:
            resources:
              requests:
                memory: "128Mi"
                cpu: "100m"
              limits:
                memory: "1028Mi"
                cpu: "1000m"
            readinessProbe:
              initialDelaySeconds: 20
              periodSeconds: 20
              failureThreshold: 5
            livenessProbe:
              initialDelaySeconds: 20
              periodSeconds: 20
              failureThreshold: 5
            strategy: RollingUpdate
            imagePullPolicy: Always
            image: wso2/router:1.0.0-beta
            # configs:
            #   tls:
            #     secretName: "router-cert"
            #     certKeyFilename: ""
            #     certFilename: ""
#            logging:
#              wireLogs:
#                enable: true
#              accessLogs:
#                enable: true
          enforcer:
            resources:
              requests:
                memory: "128Mi"
                cpu: "100m"
              limits:
                memory: "1028Mi"
                cpu: "1000m"
            readinessProbe:
              initialDelaySeconds: 20
              periodSeconds: 20
              failureThreshold: 5
            livenessProbe:
              initialDelaySeconds: 20
              periodSeconds: 20
              failureThreshold: 5
            strategy: RollingUpdate
            imagePullPolicy: Always
            image: wso2/enforcer:1.0.0-beta
            security:
              sslHostname: "enforcer"
#            logging:
#              level: DEBUG
            # configs:
            #   tls:
            #     secretName: "router-cert"
            #     certKeyFilename: ""
            #     certFilename: ""
            #   filters:
            #     - className: org.wso2.micro.gateway.enforcer.filter.RequestFilter
            #       position: 1
            #       properties:
            #         - name: filterConfig1
            #           value: filterConfig1
    migration:
      # -- This flag should be enabled only in a migration scenario.
      # -- It is not recommended to run a production deployment with this flag enabled.
      enabled: false
idp:
  enabled: true
  listener:
    hostname: "idp.am.wso2.com"
    # secretName: "idp-tls"
  database:
    driver: "org.postgresql.Driver"
    url: "jdbc:postgresql://wso2apk-db-service:5432/WSO2AM_DB"
    host: "wso2apk-db-service"
    port: 5432
    databaseName: "WSO2AM_DB"
    username: "wso2carbon"
    secretName: "apk-db-secret"
    secretKey: "DB_PASSWORD"
    validationQuery: "SELECT 1"
    validationTimeout: 250
  idpds:
    config:
      issuer: "https://idp.am.wso2.com/token"
      keyId: "gateway_certificate_alias"
      hostname: "idp.am.wso2.com"
      loginPageURl: "https://idp.am.wso2.com:9095/authenticationEndpoint/login"
      loginErrorPageUrl: "https://idp.am.wso2.com:9095/authenticationEndpoint/error"
      loginCallBackURl: "https://idp.am.wso2.com:9095/authenticationEndpoint/login-callback"
    deployment:
      resources:
        requests:
          memory: "128Mi"
          cpu: "100m"
        limits:
          memory: "1028Mi"
          cpu: "1000m"
      readinessProbe:
        initialDelaySeconds: 20
        periodSeconds: 20
        failureThreshold: 5
      livenessProbe:
        initialDelaySeconds: 20
        periodSeconds: 20
        failureThreshold: 5
      strategy: RollingUpdate
      replicas: 1
      imagePullPolicy: Always
      image: wso2/idp-domain-service:1.0.0-beta
  idpui:
    deployment:
      resources:
        requests:
          memory: "128Mi"
          cpu: "100m"
        limits:
          memory: "1028Mi"
          cpu: "1000m"
      readinessProbe:
        initialDelaySeconds: 20
        periodSeconds: 20
        failureThreshold: 5
      livenessProbe:
        initialDelaySeconds: 20
        periodSeconds: 20
        failureThreshold: 5
      strategy: RollingUpdate
      replicas: 1
      imagePullPolicy: Always
      image: wso2/idp-ui:1.0.0-beta
    configs:
      idpLoginUrl: "https://idp.am.wso2.com:9095/commonauth/login"
      idpAuthCallBackUrl: "https://idp.am.wso2.com:9095/oauth2/auth-callback"

gatewaySystem:
  enabled: true
  enableServiceAccountCreation: true
  enableClusterRoleCreation: true
  serviceAccountName: gateway-api-admission


certmanager:
  enabled: true
  enableClusterIssuer: true
  enableRootCa: true
postgresql:
  enabled: true
  fullnameOverride: "wso2apk-db-service"
  auth:
    database: WSO2AM_DB
    postgresPassword: wso2carbon
    username: wso2carbon
    password: wso2carbon
  primary:
    extendedConfiguration: |
      max_connections = 400
    initdb:
      scriptsConfigMap: postgres-initdb-scripts-configmap
      user: wso2carbon
      password: wso2carbon
    service:
      ports:
        postgresql: 5432
    podSecurityContext:
      enabled: true
      fsGroup: null
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault
    containerSecurityContext:
      enabled: true
      allowPrivilegeEscalation: false
      capabilities:
        drop: ["ALL"]
      runAsUser: null

  image:
    debug: true

redis:
  enabled: true
  architecture: standalone
  fullnameOverride: redis
  primary:
    service:
      ports:
        redis: 6379
  master:
    podSecurityContext:
      enabled: true
      fsGroup: null
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault
    containerSecurityContext:
      enabled: true
      allowPrivilegeEscalation: false
      capabilities:
        drop: ["ALL"]
      runAsUser: null
  auth:
    enabled: false
  image:
    debug: true
