# --------------------------------------------------------------------
#    Copyright (c) 2024, WSO2 LLC. (http://www.wso2.com).
#
#    WSO2 LLC. licenses this file to you under the Apache License,
#    Version 2.0 (the "License"); you may not use this file except
#    in compliance with the License.
#    You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing,
#    software distributed under the License is distributed on an
#    "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
#    KIND, either express or implied.  See the License for the
#    specific language governing permissions and limitations
#    under the License.
# -----------------------------------------------------------------------

# Config options: https://github.com/prometheus/jmx_exporter/blob/main/README.md
lowercaseOutputName: true
lowercaseOutputLabelNames: true
rules:
  # WSO2 APK related metrics
  - pattern: "org.wso2.apk.enforcer<type=ExtAuthMetrics><>total_request_count: (.*)"
    name: org_wso2_apk_enforcer_request_count_total
    help: "WSO2 APK enforcer total request count."
    attrNameSnakeCase: true
    type: COUNTER
  - pattern: "org.wso2.apk.enforcer<type=ExtAuthMetrics><>(average_response_time_millis|max_response_time_millis|min_response_time_millis|request_count_in_last_five_minute_window|request_count_window_start_time_millis|token_issuer_count|subscription_count): (.*)"
    name: org_wso2_apk_enforcer_$1
    help: "WSO2 APK enforcer $1."
    attrNameSnakeCase: true
    type: GAUGE
  - pattern: 'org.wso2.apk.enforcer.analytics<type=ExtAuthMetrics><>(subscription_count|api_messages): (.*)'
    name: org_wso2_apk_enforcer_analytics_$1
    help: "WSO2 APK enforcer analytics $1."
    attrNameSnakeCase: true
    type: GAUGE
  - pattern: 'org.wso2.apk.enforcer<type=ThreadPoolConfig><>(\w+): (.*)'
    name: org_wso2_apk_enforcer_thread_pool_$1
    help: "WSO2 APK enforcer thread pool $1."
    attrNameSnakeCase: true
    type: GAUGE
  # OS related metrics
  - pattern: 'java.lang<type=OperatingSystem><>(\w+): (.*)'
    name: os_$1
    help: Operating System $1
    attrNameSnakeCase: true
    type: GAUGE
  - pattern: 'org.wso2.apk.enforcer.analytics<type=ExtAuthMetrics><>(total_requests): (.*)'
    name: "api_http_requests_total"
    attrNameSnakeCase: true
    labels:
      method: "ALL"
  - pattern: 'org.wso2.apk.enforcer.analytics<type=ExtAuthMetrics><>(post_requests): (.*)'
    name: "api_http_requests_total"
    attrNameSnakeCase: true
    labels:
      method: "POST"
  - pattern: 'org.wso2.apk.enforcer.analytics<type=ExtAuthMetrics><>(get_requests): (.*)'
    name: "api_http_requests_total"
    attrNameSnakeCase: true
    labels:
      method: "GET"
  - pattern: 'org.wso2.apk.enforcer.analytics<type=ExtAuthMetrics><>(resource_paths): (.*)'
    name: "api_http_requests_total"
    attrNameSnakeCase: true
    labels:
      resource_paths: "$1"
  - pattern: 'org.wso2.apk.enforcer.analytics<type=ExtAuthMetrics><>(api_name): (.*)'
    name: "api_http_requests_total"
    attrNameSnakeCase: true
    labels:
      api_name: "$1"
  - pattern: 'org.wso2.apk.enforcer.analytics<type=ExtAuthMetrics><>(application_id): (.*)'
    name: "api_http_requests_total"
    attrNameSnakeCase: true
    labels:
      application_id: "$1"
  - pattern: 'org.wso2.apk.enforcer.analytics<type=ExtAuthMetrics><>(success_requests): (.*)'
    name: "api_http_requests_total"
    attrNameSnakeCase: true
    labels:
      request_status: "SUCCESS"
  - pattern: 'org.wso2.apk.enforcer.analytics<type=ExtAuthMetrics><>(failure_requests): (.*)'
    name: "api_http_requests_total"
    attrNameSnakeCase: true
    labels:
      request_status: "FAILURE"
